image : python:3.7
stages:
    - build
    - test



build:
    stage : build 
    script :
        - pip install -r src/requirements.txt
        - echo "build complete :D" 

test:
    stage : test 
    script : 
        - python manage.py test